from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from kip.domain.models import (
    ApprovedAssertion,
    ArtifactView,
    AssertionCandidate,
    ContentUnit,
    DocumentPacket,
    EmbeddableUnit,
    EmbeddingRecord,
    EmbeddingSpace,
    GraphEdge,
    GraphPath,
    GraphPathRequest,
    IngestResult,
    JobRecord,
    RequestContext,
    SearchHit,
    SearchRequest,
    StatusReport,
    VocabularyItem,
)


class RepositoryPort(Protocol):
    name: str

    def migrate(self, migrations_dir: Path) -> list[str]: ...
    def has_revision(self, context: RequestContext, source_object_id: str, sha256: str) -> bool: ...
    def ingest_packet(self, context: RequestContext, packet: DocumentPacket) -> IngestResult: ...
    def search(self, context: RequestContext, request: SearchRequest, lexemes: str) -> list[SearchHit]: ...
    def list_embeddable_units(self, context: RequestContext) -> list[EmbeddableUnit]: ...
    def save_embedding_space(self, context: RequestContext, space: EmbeddingSpace) -> EmbeddingSpace: ...
    def active_embedding_space(self, context: RequestContext) -> EmbeddingSpace | None: ...
    def activate_embedding_space(self, context: RequestContext, space_id: str) -> EmbeddingSpace: ...
    def upsert_embeddings(
        self,
        context: RequestContext,
        space_id: str,
        records: list[EmbeddingRecord],
    ) -> int: ...
    def vector_search(
        self,
        context: RequestContext,
        request: SearchRequest,
        query_embedding: list[float],
        *,
        space_id: str,
        limit: int,
    ) -> list[SearchHit]: ...
    def semantic_status(self, context: RequestContext) -> dict[str, Any]: ...
    def vocabulary(self, context: RequestContext, prefix: str, limit: int = 20) -> list[VocabularyItem]: ...
    def get_content_unit(self, context: RequestContext, unit_id: str) -> ContentUnit: ...
    def get_artifact(self, context: RequestContext, artifact_id: str) -> ArtifactView: ...
    def get_document(self, context: RequestContext, document_id: str) -> dict[str, Any]: ...
    def graph_neighbors(self, context: RequestContext, request: Any) -> list[GraphEdge]: ...
    def graph_path(self, context: RequestContext, request: GraphPathRequest) -> list[GraphPath]: ...
    def enqueue_job(self, context: RequestContext, job_type: str, payload: dict[str, Any], idempotency_key: str | None = None) -> str: ...
    def claim_job(self, context: RequestContext, worker_id: str) -> JobRecord | None: ...
    def complete_job(self, context: RequestContext, job_id: str) -> None: ...
    def fail_job(self, context: RequestContext, job_id: str, error: str) -> None: ...
    def list_jobs(self, context: RequestContext, status: str | None = None, limit: int = 100) -> list[JobRecord]: ...
    def save_candidate(self, context: RequestContext, candidate: AssertionCandidate) -> AssertionCandidate: ...
    def get_candidate(self, context: RequestContext, candidate_id: str) -> AssertionCandidate: ...
    def list_candidates(self, context: RequestContext, status: str = "proposed", limit: int = 100) -> list[AssertionCandidate]: ...
    def approve_candidate(self, context: RequestContext, candidate_id: str, reviewer_id: str, note: str | None = None) -> ApprovedAssertion: ...
    def reject_candidate(self, context: RequestContext, candidate_id: str, reviewer_id: str, note: str | None = None) -> AssertionCandidate: ...
    def get_assertion(self, context: RequestContext, assertion_id: str) -> ApprovedAssertion: ...
    def status(self, context: RequestContext) -> StatusReport: ...
    def rebuild_projection(self, context: RequestContext, projection: str) -> dict[str, Any]: ...
    def export_canonical(self, context: RequestContext, output: Path) -> dict[str, Any]: ...
